version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins_on_docker
    networks:
      - jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
