version: '3.8'

services:
  jenkins-master:
    build: .
    container_name: jenkins_master
    networks:
      - jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins_slave1
    networks:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins_master:8080
      - JENKINS_AGENT_NAME=slave1
      - JENKINS_SECRET=<agent-secret-slave1>
      - JENKINS_TUNNEL=jenkins_master:50000
    depends_on:
      - jenkins-master

  jenkins-slave2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins_slave2
    networks:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins_master:8080
      - JENKINS_AGENT_NAME=slave2
      - JENKINS_SECRET=<agent-secret-slave2>
      - JENKINS_TUNNEL=jenkins_master:50000
    depends_on:
      - jenkins-master

  jenkins-slave3:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins_slave3
    networks:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins_master:8080
      - JENKINS_AGENT_NAME=slave3
      - JENKINS_SECRET=<agent-secret-slave3>
      - JENKINS_TUNNEL=jenkins_master:50000
    depends_on:
      - jenkins-master

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
